version: '2.1'
services:
  mongodb:
    image: mongo:4.0
    container_name: mongodb_kata
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    entrypoint: ["mongod", "--smallfiles", "--logpath=/dev/null", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - "27017:27017"
#  mongoconfig:
#    build: ./mongodev
#    container_name: mongodb_kata_config
#    entrypoint: ["sh", "mongo-dev.sh" ]
#    links:
#      - mongodb
#    restart: on-failure
#    depends_on:
#      - mongodb

  mongo_seed:
    image: mongo:4.0
    container_name: mongo-seed
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    depends_on:
      - mongodb
    command: [
        "mongoimport --host mongodb --port 27017 --db mongo_kata --mode upsert --type json --file Students.json --jsonArray"
      ]
#
#  dockerhost:
#    image: qoomon/docker-host
#    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
#    mem_limit: 8M
#    restart: on-failure

