version: '2.1'
services:
  mongodb:
    image: mongo:4.0
    container_name: mongodb_kata
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    entrypoint: ["mongod", "--smallfiles", "--logpath=/dev/null", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - "27017:27017"
